logdir: 'results/'
device: cuda
use_tb: true
utd: 1
num_train_frames: 3e6
num_eval_episodes: 10
eval_every: 1e4
log_every: 2e3
save_every: 1e5
update_start: 10000

# env
task: quadruped_walk
action_repeat: 2
discount: 0.99
vision: false
height: 84  # 64
weight: 84

# replay
capacity: 2e6
ongoing: False
min_len: 50
max_len: 50
prioritize_ends: true
batch: 16
length: 50

# agent
feature_dim: 50
hidden_dim: 1024
ensemble: 1
init_temperature: 0.1
alpha_lr: 1e-4
actor_lr: 1e-4
encoder_lr: 1e-4
critic_lr: 1e-4
critic_tau: 0.005
critic_target_update_frequency: 1
learnable_temperature: true

# data distillation
use_dd: false
dd_num: 100
dd_lr: 1e-4

# replay buffer
frame_stack: 3
